# Documentation: https://goreleaser.com
---
version: 2
project_name: kusari-cli

# Environment variables required for the build
env:
  - CGO_ENABLED=0
  # - GITHUB_REPOSITORY=kuaridev/kusari-cli
  # - DOCKER_CONTEXT=default

# dockers:
#   # see details at https://goreleaser.com/customization/docker/
#   - use: buildx
#     goos: linux
#     goarch: amd64
#     image_templates:
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-amd64"
#     dockerfile: Dockerfile.goreleaser
#     build_flag_templates:
#       - "--platform=linux/amd64"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.name={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--label=org.opencontainers.image.source={{.GitURL}}"
#       - "--builder={{ .Env.DOCKER_CONTEXT }}"
#   - use: buildx
#     goos: linux
#     goarch: arm64
#     image_templates:
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-arm64"
#     dockerfile: Dockerfile.goreleaser
#     build_flag_templates:
#       - "--platform=linux/arm64"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.name={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--label=org.opencontainers.image.source={{.GitURL}}"
#       - "--builder={{ .Env.DOCKER_CONTEXT }}"

# docker_manifests:
#   - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}"
#     image_templates:
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-amd64"
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-arm64"

# docker_signs:
#   - cmd: cosign
#     artifacts: all
#     output: true
#     args:
#       - "sign"
#       - "--a"
#       - "git_sha={{.FullCommit}}"
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}@${digest}"
#       - "--yes"

# Build configuration
builds:
  - id: kusari 
    main: ./kusari
    binary: kusari
#     binary: kusari-{{ .Os }}-{{ .Arch }}
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

universal_binaries:
  - replace: true
    name_template: kusari
    id: kusari
    ids:
      - kusari 

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
    builds_info:
      group: root
      owner: root

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: SNAPSHOT-{{ .ShortCommit }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# GitHub release configuration
release:
  draft: false
  name_template: "Release {{ .Tag }}"
  disable: false

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...
