// Copyright (c) Kusari <https://www.kusari.dev/>
// SPDX-License-Identifier: MIT

// Code in this file is regenerated by scripts/bump-mikebom.sh. Do not hand-edit.

package mikebom

const (
	Version = "0.1.0-alpha.52"
	Repo    = "kusari-oss/mikebom"
)

// asset names + SHA256 hashes per GOOS/GOARCH, taken from the upstream
// release's SHA256SUMS. The hash is the trust root for verification.
//
// Intel macOS (darwin/amd64) is intentionally absent: upstream does not
// currently publish that target.
var assets = map[string]asset{
	"darwin/arm64": {
		"mikebom-v0.1.0-alpha.52-aarch64-apple-darwin.tar.gz",
		"7a6727bd6359e1b7235a87037984dd87f4f00e182b97e0d48ac994caedf0feb1",
	},
	"linux/amd64": {
		"mikebom-v0.1.0-alpha.52-x86_64-unknown-linux-gnu.tar.gz",
		"7555638e33f4819eda4df5b35ac8d589dd89611d7563d08d0afa132fcc33af8a",
	},
	"linux/arm64": {
		"mikebom-v0.1.0-alpha.52-aarch64-unknown-linux-gnu.tar.gz",
		"5208e745cb06ab32cfc91e8cf91cf203a9a3b39067dfde48f20b638f3bf866c8",
	},
}
