// Copyright (c) Kusari <https://www.kusari.dev/>
// SPDX-License-Identifier: MIT

// Code in this file is regenerated by scripts/bump-mikebom.sh. Do not hand-edit.

package mikebom

const (
	Version = "0.1.0-alpha.42"
	Repo    = "kusari-sandbox/mikebom"
)

// asset names + SHA256 hashes per GOOS/GOARCH, taken from the upstream
// release's SHA256SUMS. The hash is the trust root for verification.
//
// Intel macOS (darwin/amd64) is intentionally absent: upstream does not
// currently publish that target.
var assets = map[string]asset{
	"darwin/arm64": {
		"mikebom-v0.1.0-alpha.42-aarch64-apple-darwin.tar.gz",
		"cf5279c7a7575c545a9e001be48a6a9bf78634e225a1ef1376eb020abde73bc2",
	},
	"linux/amd64": {
		"mikebom-v0.1.0-alpha.42-x86_64-unknown-linux-gnu.tar.gz",
		"9c2116949b4cc906ce4a1e8ddbd96440a3b35a2487384406bd8ba7790092ef55",
	},
	"linux/arm64": {
		"mikebom-v0.1.0-alpha.42-aarch64-unknown-linux-gnu.tar.gz",
		"de96b958e2f34d4b2946197a928276a7189225b21ae1870dcb8535d16688bdf7",
	},
}
