// Copyright (c) Kusari <https://www.kusari.dev/>
// SPDX-License-Identifier: MIT

// Code in this file is regenerated by scripts/bump-mikebom.sh. Do not hand-edit.

package mikebom

const (
	Version = "0.1.0-alpha.64"
	Repo    = "kusari-oss/mikebom"
)

// asset names + SHA256 hashes per GOOS/GOARCH, taken from the upstream
// release's SHA256SUMS. The hash is the trust root for verification.
//
// Intel macOS (darwin/amd64) is intentionally absent: upstream does not
// currently publish that target.
var assets = map[string]asset{
	"darwin/arm64": {
		"mikebom-v0.1.0-alpha.64-aarch64-apple-darwin.tar.gz",
		"3dc135dc53df02ffb4e881f82b0f20eb4761beeb634a93d9127466dcb4bc31fb",
	},
	"linux/amd64": {
		"mikebom-v0.1.0-alpha.64-x86_64-unknown-linux-gnu.tar.gz",
		"86eb1281082ed572b0bc65b3ae0fd837e35b045d706c6947febf9889f9130427",
	},
	"linux/arm64": {
		"mikebom-v0.1.0-alpha.64-aarch64-unknown-linux-gnu.tar.gz",
		"cf78d9292937c57c7c502c4404502cdb767725a06329d489018809a83ec4d644",
	},
}
