#!/usr/bin/env bash
# Regenerate pkg/mikebom/versions.go for a given MikeBOM release tag.
#
# Usage: scripts/bump-mikebom.sh v0.1.0-alpha.33
#
# Fetches SHA256SUMS from the release, parses it, and writes the asset map
# for the GOOS/GOARCH targets we support. Windows is intentionally omitted.

set -euo pipefail

TAG="${1:-}"
if [[ -z "${TAG}" ]]; then
    echo "usage: $0 <tag> (e.g. v0.1.0-alpha.33)" >&2
    exit 2
fi
VERSION="${TAG#v}"
REPO="kusari-sandbox/mikebom"
OUT="$(cd "$(dirname "$0")/.." && pwd)/pkg/mikebom/versions.go"

SUMS="$(curl -fsSL "https://github.com/${REPO}/releases/download/${TAG}/SHA256SUMS")"

# Look up the sha256 for a given asset filename in SUMS, or empty if absent.
sha_for() {
    awk -v f="$1" '$2 == f { print $1 }' <<<"${SUMS}"
}

DARWIN_ARM64_FILE="mikebom-${TAG}-aarch64-apple-darwin.tar.gz"
LINUX_AMD64_FILE="mikebom-${TAG}-x86_64-unknown-linux-gnu.tar.gz"
LINUX_ARM64_FILE="mikebom-${TAG}-aarch64-unknown-linux-gnu.tar.gz"

DARWIN_ARM64_SHA="$(sha_for "${DARWIN_ARM64_FILE}")"
LINUX_AMD64_SHA="$(sha_for "${LINUX_AMD64_FILE}")"
LINUX_ARM64_SHA="$(sha_for "${LINUX_ARM64_FILE}")"

for pair in \
    "darwin/arm64:${DARWIN_ARM64_FILE}:${DARWIN_ARM64_SHA}" \
    "linux/amd64:${LINUX_AMD64_FILE}:${LINUX_AMD64_SHA}" \
    "linux/arm64:${LINUX_ARM64_FILE}:${LINUX_ARM64_SHA}"; do
    IFS=':' read -r target file sha <<<"${pair}"
    if [[ -z "${sha}" ]]; then
        echo "error: ${file} not found in SHA256SUMS for ${TAG}" >&2
        exit 1
    fi
done

cat >"${OUT}" <<EOF
// Copyright (c) Kusari <https://www.kusari.dev/>
// SPDX-License-Identifier: MIT

// Code in this file is regenerated by scripts/bump-mikebom.sh. Do not hand-edit.

package mikebom

const (
	Version = "${VERSION}"
	Repo    = "${REPO}"
)

// asset names + SHA256 hashes per GOOS/GOARCH, taken from the upstream
// release's SHA256SUMS. The hash is the trust root for verification.
//
// Intel macOS (darwin/amd64) is intentionally absent: upstream does not
// currently publish that target.
var assets = map[string]asset{
	"darwin/arm64": {
		"${DARWIN_ARM64_FILE}",
		"${DARWIN_ARM64_SHA}",
	},
	"linux/amd64": {
		"${LINUX_AMD64_FILE}",
		"${LINUX_AMD64_SHA}",
	},
	"linux/arm64": {
		"${LINUX_ARM64_FILE}",
		"${LINUX_ARM64_SHA}",
	},
}
EOF

gofmt -w "${OUT}"
echo "wrote ${OUT} for ${TAG}"
