// Copyright (c) Kusari <https://www.kusari.dev/>
// SPDX-License-Identifier: MIT

// Code in this file is regenerated by scripts/bump-waybill.sh. Do not hand-edit.

package waybill

const (
	Version = "0.1.0-alpha.68"
	Repo    = "kusari-oss/waybill"
)

// asset names + SHA256 hashes per GOOS/GOARCH, taken from the upstream
// release's SHA256SUMS. The hash is the trust root for verification.
//
// Intel macOS (darwin/amd64) is intentionally absent: upstream does not
// currently publish that target.
var assets = map[string]asset{
	"darwin/arm64": {
		"waybill-v0.1.0-alpha.68-aarch64-apple-darwin.tar.gz",
		"b4efbdb0bbe178d97d148e60fce3d1a2f677e290b6b796ff5dc85d9cc9f6a36d",
	},
	"linux/amd64": {
		"waybill-v0.1.0-alpha.68-x86_64-unknown-linux-gnu.tar.gz",
		"49831ef340d1dd170a2c593ee75f5515213dd83aba9558e4da734e95b6847fcc",
	},
	"linux/arm64": {
		"waybill-v0.1.0-alpha.68-aarch64-unknown-linux-gnu.tar.gz",
		"4b603667bd9df3648a872fb087417541bbe68c34b0a27ad31379a3292995aeac",
	},
}
